Transform: AWS::Serverless-2016-10-31
Resources:
  WechatLambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: WechatLayer
      Description: v.1.0.0
      ContentUri: s3://wechat-layer-prod-serverlessdeploymentbucket-1ld0jpbs69ge9/214d3df5379a9a529d35a172e61046fe
      CompatibleRuntimes:
      - python3.6
      - python3.7
      - python3.8
Outputs:
  WechatLambdaLayer:
    Value:
      Ref: WechatLambdaLayer
