Transform: AWS::Serverless-2016-10-31
Metadata:
  AWS::ServerlessRepo::Application:
    Name: enterprise-wechat-lambda-layer
    Description: Enterprise Wechat Lambda Layer - Produced by Niko Feng(nikosheng@gmail.com)
    Author: nikosheng
    SpdxLicenseId: Apache-2.0
    LicenseUrl: s3://aws-nikofeng-serverless-application-repo/3b83ef96387f14655fc854ddc3c6bd57
    ReadmeUrl: s3://aws-nikofeng-serverless-application-repo/fc3d99158da4d0b49970f43f92700c92
    Labels:
    - wechat
    - lambda-layer
    HomePageUrl: https://github.com/nikosheng/wechat-lambda-layer-sam
    SemanticVersion: 1.0.5
    SourceCodeUrl: https://github.com/nikosheng/wechat-lambda-layer-sam
Resources:
  WechatLambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: WechatLayer
      Description: v.1.0.5
      ContentUri: s3://aws-nikofeng-serverless-application-repo/bff7851250d52c6970807f7929141c66
      CompatibleRuntimes:
      - python3.6
      - python3.7
      - python3.8
Outputs:
  WechatLambdaLayer:
    Value:
      Ref: WechatLambdaLayer
